import { createFileRoute } from "@tanstack/react-router";
import { EmailField, Field, SelectField, SubmissionForm, TextArea, UrlField } from "@/components/CommunityForms";
import image from "@/assets/editorial-film.jpg";

export const Route = createFileRoute("/collective")({
  staticData: { sitemap: true },
  head: () => ({ meta: [
    { title: "Collective | H-Visuals" }, { name: "description", content: "H-Visuals Collective assembles the right creative professionals for each visual brief." },
    { property: "og:title", content: "H-Visuals Collective" }, { property: "og:description", content: "Creative power, collective force. One standard for every brief." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: CollectivePage,
});

function CollectivePage() { return <main className="bg-ink text-cream pt-24">
  <section className="relative flex min-h-[75svh] items-end overflow-hidden"><img src={image} alt="Nigerian creative professionals collaborating on a film set" className="absolute inset-0 h-full w-full object-cover" /><div className="service-card-overlay absolute inset-0" /><div className="studio-shell relative z-10 pb-16 pt-32"><p className="editorial-label text-sunshine">H-Visuals Collective</p><h1 className="community-heading max-w-5xl text-cream">Creative power,<br /> collective force.</h1><p className="mt-8 max-w-2xl text-xl text-cream/85">H-Visuals Collective is a curated network of creative professionals who come together to deliver visual solutions for brands. Any brief. Any scale. One standard.</p></div></section>
  <section className="community-section"><div className="studio-shell"><p className="editorial-label text-sunshine">The process</p><h2 className="community-heading text-cream">How it works</h2><div className="mt-12 grid border-t border-cream/30 md:grid-cols-3">{[["01", "Submit Brief", "Tell us what you're building and what you need."], ["02", "We Assemble the Team", "We bring together the right creatives from the network."], ["03", "Work Gets Done", "The work is delivered under the H-Visuals quality standard."]].map(([n, title, copy]) => <div key={n} className="border-b border-cream/30 p-6 md:border-r"><span className="font-mono text-sunshine">{n}</span><h3 className="mt-12 text-2xl text-cream">{title}</h3><p className="mt-4 text-cream/70">{copy}</p></div>)}</div></div></section>
  <section className="community-section bg-ink-surface"><div className="studio-shell grid gap-16 lg:grid-cols-2"><div><p className="editorial-label text-sunshine">For clients</p><h2 className="community-heading text-cream">Have a project?</h2><p className="my-8 text-cream/75">Submit your brief and we'll put the right creative team together for it.</p><SubmissionForm kind="collective_brief" label="Submit Brief"><Field label="Name" name="name" required /><Field label="Brand or Business Name" name="brand" required /><EmailField /><Field label="Project Type" name="projectType" required><SelectField name="projectType" required options={["Brand Identity", "Video Production", "Content Creation", "Social Media", "Campaign", "Other"]} /></Field><Field label="Project Description" name="description" required><TextArea name="description" required /></Field><Field label="Timeline (optional)" name="timeline" /><Field label="Budget Range (optional)" name="budget"><SelectField name="budget" options={["Under ₦500k", "₦500k–₦2M", "₦2M–₦5M", "₦5M+", "Prefer not to say"]} /></Field></SubmissionForm></div><div className="border-t border-sunshine pt-12 lg:border-l lg:border-t-0 lg:pl-12 lg:pt-0"><p className="editorial-label text-sunshine">For creatives</p><h2 className="community-heading text-cream">Want to join?</h2><p className="my-8 text-cream/75">The Collective is open to any creative who wants to collaborate on real projects with a brand that takes the work seriously.</p><SubmissionForm kind="collective_creative" label="Express Interest"><Field label="Name" name="name" required /><EmailField /><Field label="Creative Discipline" name="discipline" required><SelectField name="discipline" required options={["Graphic Design", "Video/Film", "Photography", "Motion Design", "Copywriting", "Art Direction", "Social Media", "Other"]} /></Field><UrlField label="Portfolio Link" name="portfolio" required /><Field label="Short Note" name="note" required><TextArea name="note" required placeholder="Tell us what kind of work you do" /></Field></SubmissionForm></div></div></section>
</main>; }