import { createFileRoute } from "@tanstack/react-router";
import { SignupForm } from "@/components/CommunityForms";
import image from "@/assets/editorial-strategy.jpg";

export const Route = createFileRoute("/focal")({ staticData: { sitemap: true }, head: () => ({ meta: [
  { title: "Focal by H-Visuals | Visual Strategy" }, { name: "description", content: "Focal helps you decide what to make, who it is for and what it should say before you open a design tool." },
  { property: "og:title", content: "Focal by H-Visuals" }, { property: "og:description", content: "Before you create anything — know exactly what to say." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: FocalPage });

const steps = ["Define your objective", "Know your audience", "Clarify your message", "Choose your feeling", "Build your visual concept", "Identify your assets", "Build your content system"];
function FocalPage() { return <main className="bg-ink text-cream pt-24"><section className="studio-shell community-section grid items-center gap-12 lg:grid-cols-2"><div><p className="editorial-label text-sunshine">Focal by H-Visuals</p><h1 className="community-heading text-cream">Before you create anything — know exactly what to say.</h1><p className="mt-8 max-w-xl text-lg text-cream/75">Most tools help you make things. Focal helps you figure out what to make, for whom, with what message, and how it should look — before you open any design tool.</p><a href="#waitlist" className="studio-button-sun mt-8">Join the Waitlist →</a></div><div className="editorial-media aspect-[4/5] overflow-hidden"><img src={image} alt="A Nigerian creative director developing a visual strategy" className="h-full w-full object-cover" /></div></section><section className="community-section bg-ink-surface"><div className="studio-shell"><p className="editorial-label text-sunshine">The thinking before the making</p><h2 className="community-heading max-w-5xl text-cream">The gap between having an idea and communicating it visually is where most brands lose.</h2><p className="mt-10 max-w-3xl text-xl text-cream/75">Focal fills that gap. It's an AI-powered visual strategy platform that walks you through the thinking — objective, audience, message, feeling, visual concept, assets, system — so that every creative decision has a reason behind it.</p></div></section><section className="community-section"><div className="studio-shell"><p className="editorial-label text-sunshine">The framework</p><h2 className="community-heading text-cream">Seven steps to clarity.</h2><ol className="mt-12 grid border-t border-cream/30 md:grid-cols-2">{steps.map((step, i) => <li key={step} className="flex gap-8 border-b border-cream/30 py-7 md:px-6"><span className="font-mono text-sunshine">0{i + 1}</span><span className="font-display text-xl text-cream">{step}</span></li>)}</ol></div></section><section className="community-section bg-ink-surface"><div className="studio-shell"><blockquote className="max-w-5xl border-l-4 border-sunshine pl-8 font-serif text-3xl italic leading-tight text-cream md:text-5xl">Focal sits above Canva, Adobe and Midjourney. It doesn't replace them. It tells you what to do with them.</blockquote></div></section><section id="waitlist" className="community-section scroll-mt-24"><div className="studio-shell max-w-4xl"><p className="editorial-label text-sunshine">Early access</p><h2 className="community-heading text-cream">Join the Waitlist</h2><div className="mt-10"><SignupForm source="focal_waitlist" label="Get Early Access" /></div><p className="mt-5 text-sm text-cream/65">Focal is currently in development. Early access members will be notified first.</p></div></section></main>; }