import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { EmailField, Field, SubmissionForm, SignupForm, TextArea, UrlField } from "@/components/CommunityForms";
import { Publications, Resources } from "@/components/CommunitySections";
import image from "@/assets/editorial-social.jpg";

export const Route = createFileRoute("/infovibes")({ staticData: { sitemap: true }, head: () => ({ meta: [
  { title: "Infovibes | H-Visuals" }, { name: "description", content: "A community and media platform where creatives learn, share and grow." },
  { property: "og:title", content: "Infovibes | Where creatives learn, share and grow" }, { property: "og:description", content: "Writing, shared process and creative reflection from the Infovibes community." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: InfovibesPage });

type Piece = { id: string; name: string; details: { title?: string; content?: string; draft?: string } };
function CreativeDump() {
  const [pieces, setPieces] = useState<Piece[]>([]);
  useEffect(() => { let active = true; supabase.from("studio_submissions").select("id,name,details").eq("kind", "creative_dump").eq("status", "approved").order("created_at", { ascending: false }).then(({ data }) => { if (active) setPieces((data ?? []) as Piece[]); }); return () => { active = false; }; }, []);
  return <section className="community-section bg-ink-surface text-cream"><div className="studio-shell"><p className="editorial-label text-sunshine">Open platform</p><h2 className="community-heading text-cream">The Creative Dump</h2><p className="mt-7 max-w-3xl text-lg text-cream/75">An open platform for creatives to share reviews, criticism, process writing and reflections. If you make things, this is where you write about it.</p><div className="mt-12 grid gap-5 md:grid-cols-2">{pieces.length ? pieces.map(piece => <article key={piece.id} className="border-t border-sunshine bg-ink p-6"><h3 className="text-2xl text-cream">{piece.details.title}</h3><p className="mt-2 font-mono text-xs text-sunshine">By {piece.name}</p>{piece.details.content && <p className="mt-5 whitespace-pre-wrap text-cream/75">{piece.details.content}</p>}{piece.details.draft && <a className="studio-text-link mt-5 text-sunshine" href={piece.details.draft} target="_blank" rel="noopener noreferrer">Read the piece →</a>}</article>) : <p className="border-t border-cream/30 py-8 font-serif text-2xl italic text-cream/70">No pieces published yet — be the first to submit.</p>}</div><div className="mt-16 grid gap-14 border-t border-cream/30 pt-14 lg:grid-cols-2"><div><h3 className="font-display text-3xl text-cream">Submit your piece</h3><p className="mb-7 text-cream/70">All submissions are reviewed before going live.</p><SubmissionForm kind="creative_dump" label="Submit Your Piece"><Field label="Name" name="name" required /><EmailField /><Field label="Title of Piece" name="title" required /><Field label="Written Content" name="content"><TextArea name="content" /></Field><p className="text-sm text-cream/65">Include your writing or a link to your draft.</p><UrlField label="Link to Draft (optional)" name="draft" /></SubmissionForm></div><div className="lg:border-l lg:border-sunshine lg:pl-12"><h3 className="font-display text-3xl text-cream">Follow the conversation</h3><p className="my-7 text-cream/70">Get notified when new pieces are published.</p><SignupForm source="creative_dump_updates" label="Subscribe" requireName={false} /></div></div></div></section>;
}
function InfovibesPage() { return <main className="pt-24 bg-ink text-cream"><header className="relative flex min-h-[70svh] items-end overflow-hidden"><img src={image} alt="Nigerian creatives sharing ideas in a studio" className="absolute inset-0 h-full w-full object-cover" /><div className="service-card-overlay absolute inset-0" /><div className="studio-shell relative z-10 pb-16 pt-32"><p className="editorial-label text-sunshine">Infovibes</p><h1 className="community-heading max-w-5xl text-cream">Where creatives learn, share and grow.</h1><p className="mt-7 max-w-xl text-xl text-cream/80">A community and media platform for people who take their creative work seriously.</p></div></header><Publications prominent /><CreativeDump /><Resources /></main>; }